//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <summary>
/// Units for area measurement, do we need to consider imperial?
/// </summary>
public enum AreaUnits : int
{
	squaremeters,
	squarecentimeters,
	squaremillimeters,
	squarekilometers,
}
