//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <summary>
/// Units for currency measurement, these are define as 3 character codes in ISO  4217
/// </summary>
public enum CurrencyUnits : int
{
	/// <summary>
	/// United States Dollar
	/// </summary>
	USD,
	/// <summary>
	/// Currency of the European Union States in monetary union Euro
	/// </summary>
	EUR,
	/// <summary>
	/// British Pound Stirling
	/// </summary>
	GBP,
}
