//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <summary>
/// The classification system used throughout this work package
/// </summary>
public interface IClassification 
{
	/// <summary>
	/// URI to follow to the location of the published classification
	/// </summary>
	string ClassificationURI { get;set; }

	/// <summary>
	/// The date on which the edition of the classification used became valid.
	/// </summary>
	string ClassificationEditionDate { get;set; }

	/// <summary>
	/// Full name of the classification system
	/// </summary>
	string ClassificationName { get;set; }

	/// <summary>
	/// The edition of the classification system i.e. UniClass 3
	/// </summary>
	string ClassificationEdition { get;set; }

	/// <summary>
	/// Name of the publisher
	/// </summary>
	string ClassificationPublisher { get;set; }

	/// <summary>
	/// Classification references used only in this project
	/// </summary>
	IEnumerable<IClassificationReference> ClassificationReferences { get;set; }

}

