//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <summary>
/// A participant in the project
/// </summary>
public interface IContact 
{
	string ContactCompanyName { get;set; }

	string ContactDepartmentName { get;set; }

	string ContactTownName { get;set; }

	string ContactRole { get;set; }

	string ContactGivenName { get;set; }

	string ContactFamilyName { get;set; }

	string ContactEmail { get;set; }

	string ContactPhoneNumber { get;set; }

	string ContactURL { get;set; }

	string ContactStreet { get;set; }

	string ContactPostCode { get;set; }

	string ContactCountry { get;set; }

	string ContactRegion { get;set; }

	string ContactPostalBox { get;set; }

}

