//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <summary>
/// A Document or a set of documents that are required to be delivered
/// </summary>
public interface IDocument 
{
	/// <summary>
	/// The scope that this document should apply to default to Facility
	/// </summary>
	ScopeOfDocument Scope { get;set; }

	string DocumentDescription { get;set; }

	string DocumentURI { get;set; }

	IClassification DocumentCategory { get;set; }

	string DocumentName { get;set; }

}

