//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <summary>
/// Anobject is a BIM object or a set of BIM objects that share a common set of properties
/// </summary>
public interface IDPoWObject 
{
	IClassificationReference DPoWObjectCategory { get;set; }

	string DPoWObjectName { get;set; }

	string DPoWObjectDescription { get;set; }

	IEnumerable<IRequiredAttribute> RequiredAttributes { get;set; }

	IRequiredLOD RequiredLOD { get;set; }

}

