//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <summary>
/// The facility that this work package is delivering part of
/// </summary>
public interface IFacility 
{
	/// <summary>
	/// Name of the facility being delivered
	/// </summary>
	string FacilityName { get;set; }

	/// <summary>
	/// Description of the facility being delivered
	/// </summary>
	string FacilityDescription { get;set; }

	/// <summary>
	/// Classification of the facility type En-
	/// </summary>
	IClassificationReference FacilityCategory { get;set; }

	string FacilitySiteName { get;set; }

	string FacilitySiteDescription { get;set; }

}

