//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <summary>
/// The aspects that are being delivered by this Plan of Work
/// </summary>
public interface IJob 
{
	string JobName { get;set; }

	string JobDescription { get;set; }

	IEnumerable<IDPoWObject>  DPoWObjects { get;set; }

	IEnumerable<IDocument> Documents { get;set; }

	/// <summary>
	/// The person or organisation that is delivering the work package
	/// </summary>
	IContact ResponsibleFor { get;set; }

}

