//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <summary>
/// The top level item for this work package
/// </summary>
public interface IPlanOfWork 
{
	/// <summary>
	/// The classification system to be used in this work package
	/// </summary>
	IEnumerable<IClassification> ClassificationSystem { get;set; }

	/// <summary>
	/// The project this work package is delivering for, i.e HS2 rail
	/// </summary>
	IProject Project { get;set; }

	/// <summary>
	/// The specific facility within the project that is being delivered for, i.e. station 47 on HS2
	/// </summary>
	IFacility Facility { get;set; }

	/// <summary>
	/// The stage this work package is delivering in to , i.e. Stage 0 feasibility
	/// </summary>
	IEnumerable<IProjectStage> ProjectStages { get;set; }

	IContact Client { get;set; }

	IEnumerable<IContact> Contacts { get;set; }

}

