//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <summary>
/// A property or attribute that must be specified in the DPoW submission
/// </summary>
public interface IRequiredAttribute 
{
	string AttributeName { get;set; }

	string AttributeDescription { get;set; }

}

