//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <summary>
/// The Level of Detail required for this DPoW Object
/// </summary>
public interface IRequiredLOD 
{
	string RequiredLODCode { get;set; }

	string RequiredLODURI { get;set; }

	string RequiredLODDescription { get;set; }

}

