//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <summary>
/// The COBie scope that a document applies to, in the early releases these all default to Facility
/// </summary>
public enum ScopeOfDocument : int
{
	/// <summary>
	/// Instance of a Space
	/// </summary>
	Space,
	Facility,
	/// <summary>
	/// An NBS Space Type
	/// </summary>
	Zone,
	/// <summary>
	/// A collection of Assets that perform a function
	/// </summary>
	System,
	/// <summary>
	/// A NBS Product Instance
	/// </summary>
	Asset,
	/// <summary>
	/// An NBS Product
	/// </summary>
	AssetType,
	/// <summary>
	/// An NBS System
	/// </summary>
	Assembly,
}
