//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <summary>
/// Units for volume measurement, do we need to consider imperial
/// </summary>
public enum VolumeUnits : int
{
	cubicmeters,
	cubicmillimeters,
	cubiccentimeters,
	cubickilometers,
}
