//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ValidationResult 
{
    public ValidationResult(IValidationRequirement validationRequirement)
    {
        ValidationRequirement = validationRequirement;
    }

	IValidationRequirement ValidationRequirement { get;set; }

	bool ValidationPassed { get;set; }

	string ValidationMessage { get;set; }

    IEnumerable<ValidationResult> InnerResults { get; set; }

}

