// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.20792 Microsoft Reciprocal License (Ms-RL) 
//    <NameSpace>Xbim.COBieLiteUK2</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><OrderXMLAttrib>True</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>False</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace Xbim.COBieLiteUK2
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://openbim.org/schemas/cobieliteuk")]
    [System.Xml.Serialization.XmlRootAttribute("Project", Namespace = "http://openbim.org/schemas/cobieliteuk", IsNullable = false)]
    public partial class ProjectType : CobieObject
    {

        private string descriptionField;

        private string addressField;

        private string functionField;

        private string procurementField;

        private double functionalUnitField;

        private bool functionalUnitFieldSpecified;

        private double expectedLifeCycleField;

        private bool expectedLifeCycleFieldSpecified;

        private decimal costField;

        private bool costFieldSpecified;

        private System.DateTime constructionStartField;

        private bool constructionStartFieldSpecified;

        private System.DateTime constructionEndField;

        private bool constructionEndFieldSpecified;

        private string externalSystemField;

        private string externalEntityField;

        private string externalIDField;

        private List<FacilityType> facilitiesField;

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string Function
        {
            get
            {
                return this.functionField;
            }
            set
            {
                this.functionField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string Procurement
        {
            get
            {
                return this.procurementField;
            }
            set
            {
                this.procurementField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public double FunctionalUnit
        {
            get
            {
                return this.functionalUnitField;
            }
            set
            {
                this.functionalUnitField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FunctionalUnitSpecified
        {
            get
            {
                return this.functionalUnitFieldSpecified;
            }
            set
            {
                this.functionalUnitFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public double ExpectedLifeCycle
        {
            get
            {
                return this.expectedLifeCycleField;
            }
            set
            {
                this.expectedLifeCycleField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExpectedLifeCycleSpecified
        {
            get
            {
                return this.expectedLifeCycleFieldSpecified;
            }
            set
            {
                this.expectedLifeCycleFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public decimal Cost
        {
            get
            {
                return this.costField;
            }
            set
            {
                this.costField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CostSpecified
        {
            get
            {
                return this.costFieldSpecified;
            }
            set
            {
                this.costFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date", Order = 7)]
        public System.DateTime ConstructionStart
        {
            get
            {
                return this.constructionStartField;
            }
            set
            {
                this.constructionStartField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ConstructionStartSpecified
        {
            get
            {
                return this.constructionStartFieldSpecified;
            }
            set
            {
                this.constructionStartFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date", Order = 8)]
        public System.DateTime ConstructionEnd
        {
            get
            {
                return this.constructionEndField;
            }
            set
            {
                this.constructionEndField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ConstructionEndSpecified
        {
            get
            {
                return this.constructionEndFieldSpecified;
            }
            set
            {
                this.constructionEndFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 9)]
        public string ExternalSystem
        {
            get
            {
                return this.externalSystemField;
            }
            set
            {
                this.externalSystemField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 10)]
        public string ExternalEntity
        {
            get
            {
                return this.externalEntityField;
            }
            set
            {
                this.externalEntityField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 11)]
        public string ExternalID
        {
            get
            {
                return this.externalIDField;
            }
            set
            {
                this.externalIDField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("Facilities", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 12)]
        public List<FacilityType> Facilities
        {
            get
            {
                return this.facilitiesField;
            }
            set
            {
                this.facilitiesField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://openbim.org/schemas/cobieliteuk")]
    [System.Xml.Serialization.XmlRootAttribute("Facility", Namespace = "http://openbim.org/schemas/cobieliteuk", IsNullable = false)]
    public partial class FacilityType : CobieObject
    {
    }

    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ZoneType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SystemType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SpareType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SpaceType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResourceType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(JobType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FloorType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContactType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ConnectionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ObjectInfoType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AssetTypeInfoType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AssetInfoType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AssemblyType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FacilityType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProjectType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IssueType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AttributeType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DocumentType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://openbim.org/schemas/cobieliteuk")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://openbim.org/schemas/cobieliteuk", IsNullable = true)]
    public partial class CobieObject
    {

        private string nameField;

        private ContactKeyType creationAssignmentField;

        private System.DateTime createdOnField;

        private bool createdOnFieldSpecified;

        private List<DocumentType> documentsField;

        private List<AttributeType> attributesField;

        private List<IssueType> issuesField;

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public ContactKeyType CreationAssignment
        {
            get
            {
                return this.creationAssignmentField;
            }
            set
            {
                this.creationAssignmentField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public System.DateTime CreatedOn
        {
            get
            {
                return this.createdOnField;
            }
            set
            {
                this.createdOnField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CreatedOnSpecified
        {
            get
            {
                return this.createdOnFieldSpecified;
            }
            set
            {
                this.createdOnFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("Documents", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public List<DocumentType> Documents
        {
            get
            {
                return this.documentsField;
            }
            set
            {
                this.documentsField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("Attributes", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public List<AttributeType> Attributes
        {
            get
            {
                return this.attributesField;
            }
            set
            {
                this.attributesField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("Issues", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public List<IssueType> Issues
        {
            get
            {
                return this.issuesField;
            }
            set
            {
                this.issuesField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://openbim.org/schemas/cobieliteuk")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://openbim.org/schemas/cobieliteuk", IsNullable = true)]
    public partial class ContactKeyType
    {

        private string emailField;

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://openbim.org/schemas/cobieliteuk")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://openbim.org/schemas/cobieliteuk", IsNullable = true)]
    public partial class AssetInfoKeyType
    {

        private string nameField;

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://openbim.org/schemas/cobieliteuk")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://openbim.org/schemas/cobieliteuk", IsNullable = true)]
    public partial class SpaceKeyType
    {

        private string nameField;

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://openbim.org/schemas/cobieliteuk")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://openbim.org/schemas/cobieliteuk", IsNullable = true)]
    public partial class DocumentType : CobieObject
    {
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://openbim.org/schemas/cobieliteuk")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://openbim.org/schemas/cobieliteuk", IsNullable = true)]
    public partial class AttributeType : CobieObject
    {
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://openbim.org/schemas/cobieliteuk")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://openbim.org/schemas/cobieliteuk", IsNullable = true)]
    public partial class IssueType : CobieObject
    {
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://openbim.org/schemas/cobieliteuk")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://openbim.org/schemas/cobieliteuk", IsNullable = true)]
    public partial class ZoneType : CobieObject
    {
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://openbim.org/schemas/cobieliteuk")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://openbim.org/schemas/cobieliteuk", IsNullable = true)]
    public partial class SystemType : CobieObject
    {
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://openbim.org/schemas/cobieliteuk")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://openbim.org/schemas/cobieliteuk", IsNullable = true)]
    public partial class SpareType : CobieObject
    {
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://openbim.org/schemas/cobieliteuk")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://openbim.org/schemas/cobieliteuk", IsNullable = true)]
    public partial class SpaceType : CobieObject
    {

        private List<AssetInfoKeyType> assetAssignmentsField;

        [System.Xml.Serialization.XmlElementAttribute("AssetAssignments", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public List<AssetInfoKeyType> AssetAssignments
        {
            get
            {
                return this.assetAssignmentsField;
            }
            set
            {
                this.assetAssignmentsField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://openbim.org/schemas/cobieliteuk")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://openbim.org/schemas/cobieliteuk", IsNullable = true)]
    public partial class ResourceType : CobieObject
    {
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://openbim.org/schemas/cobieliteuk")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://openbim.org/schemas/cobieliteuk", IsNullable = true)]
    public partial class JobType : CobieObject
    {
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://openbim.org/schemas/cobieliteuk")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://openbim.org/schemas/cobieliteuk", IsNullable = true)]
    public partial class FloorType : CobieObject
    {
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://openbim.org/schemas/cobieliteuk")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://openbim.org/schemas/cobieliteuk", IsNullable = true)]
    public partial class ContactType : CobieObject
    {
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://openbim.org/schemas/cobieliteuk")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://openbim.org/schemas/cobieliteuk", IsNullable = true)]
    public partial class ConnectionType : CobieObject
    {
    }

    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AssetTypeInfoType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AssetInfoType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://openbim.org/schemas/cobieliteuk")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://openbim.org/schemas/cobieliteuk", IsNullable = true)]
    public partial class ObjectInfoType : CobieObject
    {

        private List<AssemblyType> assembliesField;

        [System.Xml.Serialization.XmlElementAttribute("Assemblies", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public List<AssemblyType> Assemblies
        {
            get
            {
                return this.assembliesField;
            }
            set
            {
                this.assembliesField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://openbim.org/schemas/cobieliteuk")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://openbim.org/schemas/cobieliteuk", IsNullable = true)]
    public partial class AssemblyType : CobieObject
    {

        private string assemblyTypeNameField;

        private string externalSystemField;

        private string externalEntityField;

        private string externalIDField;

        private string descriptionField;

        private List<ObjectInfoType> objectsField;

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string AssemblyTypeName
        {
            get
            {
                return this.assemblyTypeNameField;
            }
            set
            {
                this.assemblyTypeNameField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string ExternalSystem
        {
            get
            {
                return this.externalSystemField;
            }
            set
            {
                this.externalSystemField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string ExternalEntity
        {
            get
            {
                return this.externalEntityField;
            }
            set
            {
                this.externalEntityField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string ExternalID
        {
            get
            {
                return this.externalIDField;
            }
            set
            {
                this.externalIDField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("Objects", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public List<ObjectInfoType> Objects
        {
            get
            {
                return this.objectsField;
            }
            set
            {
                this.objectsField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://openbim.org/schemas/cobieliteuk")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://openbim.org/schemas/cobieliteuk", IsNullable = true)]
    public partial class AssetTypeInfoType : ObjectInfoType
    {

        private string categoryField;

        private string descriptionField;

        private string assetTypeField;

        private ContactKeyType manufacturerAssignmentField;

        private string modelNumberField;

        private ContactKeyType warrantyGuarantorPartsAssignmentField;

        private double warrantyDurationPartsField;

        private bool warrantyDurationPartsFieldSpecified;

        private ContactKeyType warrantyGuarantorLaborAssignmentField;

        private double warrantyDurationLaborField;

        private bool warrantyDurationLaborFieldSpecified;

        private string warrantyDurationUnitField;

        private string externalSystemField;

        private string externalEntityField;

        private string externalIDField;

        private List<AssetInfoType> assetsField;

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string Category
        {
            get
            {
                return this.categoryField;
            }
            set
            {
                this.categoryField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string AssetType
        {
            get
            {
                return this.assetTypeField;
            }
            set
            {
                this.assetTypeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public ContactKeyType ManufacturerAssignment
        {
            get
            {
                return this.manufacturerAssignmentField;
            }
            set
            {
                this.manufacturerAssignmentField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string ModelNumber
        {
            get
            {
                return this.modelNumberField;
            }
            set
            {
                this.modelNumberField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public ContactKeyType WarrantyGuarantorPartsAssignment
        {
            get
            {
                return this.warrantyGuarantorPartsAssignmentField;
            }
            set
            {
                this.warrantyGuarantorPartsAssignmentField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public double WarrantyDurationParts
        {
            get
            {
                return this.warrantyDurationPartsField;
            }
            set
            {
                this.warrantyDurationPartsField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WarrantyDurationPartsSpecified
        {
            get
            {
                return this.warrantyDurationPartsFieldSpecified;
            }
            set
            {
                this.warrantyDurationPartsFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
        public ContactKeyType WarrantyGuarantorLaborAssignment
        {
            get
            {
                return this.warrantyGuarantorLaborAssignmentField;
            }
            set
            {
                this.warrantyGuarantorLaborAssignmentField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 8)]
        public double WarrantyDurationLabor
        {
            get
            {
                return this.warrantyDurationLaborField;
            }
            set
            {
                this.warrantyDurationLaborField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WarrantyDurationLaborSpecified
        {
            get
            {
                return this.warrantyDurationLaborFieldSpecified;
            }
            set
            {
                this.warrantyDurationLaborFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 9)]
        public string WarrantyDurationUnit
        {
            get
            {
                return this.warrantyDurationUnitField;
            }
            set
            {
                this.warrantyDurationUnitField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 10)]
        public string ExternalSystem
        {
            get
            {
                return this.externalSystemField;
            }
            set
            {
                this.externalSystemField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 11)]
        public string ExternalEntity
        {
            get
            {
                return this.externalEntityField;
            }
            set
            {
                this.externalEntityField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 12)]
        public string ExternalID
        {
            get
            {
                return this.externalIDField;
            }
            set
            {
                this.externalIDField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("Assets", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 13)]
        public List<AssetInfoType> Assets
        {
            get
            {
                return this.assetsField;
            }
            set
            {
                this.assetsField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://openbim.org/schemas/cobieliteuk")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://openbim.org/schemas/cobieliteuk", IsNullable = true)]
    public partial class AssetInfoType : ObjectInfoType
    {

        private SpaceKeyType spaceAssignmentField;

        private string descriptionField;

        private string externalSystemField;

        private string externalEntityField;

        private string externalIDField;

        private string serialNumberField;

        private System.DateTime instalationDateField;

        private System.DateTime warrantyStartDateField;

        private string tagNumberField;

        private string barCodeField;

        private string assetIdentifierField;

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public SpaceKeyType SpaceAssignment
        {
            get
            {
                return this.spaceAssignmentField;
            }
            set
            {
                this.spaceAssignmentField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string ExternalSystem
        {
            get
            {
                return this.externalSystemField;
            }
            set
            {
                this.externalSystemField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string ExternalEntity
        {
            get
            {
                return this.externalEntityField;
            }
            set
            {
                this.externalEntityField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string ExternalID
        {
            get
            {
                return this.externalIDField;
            }
            set
            {
                this.externalIDField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public string SerialNumber
        {
            get
            {
                return this.serialNumberField;
            }
            set
            {
                this.serialNumberField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public System.DateTime InstalationDate
        {
            get
            {
                return this.instalationDateField;
            }
            set
            {
                this.instalationDateField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
        public System.DateTime WarrantyStartDate
        {
            get
            {
                return this.warrantyStartDateField;
            }
            set
            {
                this.warrantyStartDateField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 8)]
        public string TagNumber
        {
            get
            {
                return this.tagNumberField;
            }
            set
            {
                this.tagNumberField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 9)]
        public string BarCode
        {
            get
            {
                return this.barCodeField;
            }
            set
            {
                this.barCodeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 10)]
        public string AssetIdentifier
        {
            get
            {
                return this.assetIdentifierField;
            }
            set
            {
                this.assetIdentifierField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://openbim.org/schemas/cobieliteuk")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://openbim.org/schemas/cobieliteuk", IsNullable = true)]
    public partial class ProjectKeyType
    {

        private string nameField;

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
}
